# Use the official image as a parent image
FROM node:20.16.0

# Set the working directory
WORKDIR /usr/src/app

# Copy the local files to the container
COPY . .

# Install dependencies
RUN npm install

# Expose the port your app runs on
EXPOSE 8080

# Command to run your app
CMD ["npm", "start"]
